use_default_settings:
  engines:
    keep_only:
      - google images
      - brave.images
      - bing images
      - duckduckgo images

general:
  debug: false
  instance_name: Context TG Image Search
  enable_metrics: false

search:
  safe_search: 0
  autocomplete: ""
  favicon_resolver: ""
  ban_time_on_fail: 0
  max_ban_time_on_fail: 0
  suspended_times:
    SearxEngineAccessDenied: 0
    SearxEngineCaptcha: 0
    SearxEngineTooManyRequests: 0
    cf_SearxEngineCaptcha: 0
    cf_SearxEngineAccessDenied: 0
    recaptcha_SearxEngineCaptcha: 0
  formats:
    - json

server:
  secret_key: context-tg-internal-image-search
  limiter: false
  public_instance: false
  image_proxy: false
  method: GET

valkey:
  url: false

plugins: {}

engines:
  - name: google images
    inactive: false
    disabled: false
  - name: brave.images
    network: ipv4
    inactive: false
    disabled: false
  - name: bing images
    inactive: false
    disabled: false
  - name: duckduckgo images
    inactive: false
    disabled: false
